package:
  name: xicam-saxs
  version: 1.2.21

source:
  git_url: https://github.com/ronpandolfi/Xi-cam.git
  git_tag: saxs-conda


build:
    osx_is_app: False
    entry_points:
        - xicam = xicamlauncher.main:main
    skip_compile_pyc:
        - buildapp.py
        - buildexe.py
        - run_xicam.py
        - setup.py
        - test.py

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython

  run:
    - scipy
    - cython
    - h5py
    - shiboken
    - pyside 1.2.4
    - scikit-image
    - pyfai
    - fabio
    - pyqtgraph
    - pillow
    - pyopengl
    - pyyaml
    - requests
    - appdirs
    - futures
    - numpy
    - setuptools
    - numexpr
    - six
    - ipython
    - psutil
    - imageio
    - vispy
    - tifffile
    - pysftp
    - qtconsole
    - qt 4.8.7*
    
about:
  home: https://github.com/ronpandolfi/Xi-cam
  summary: Xi-cam build for Synchrotron (GI)SAXS analysis
